In [66]:
from sklearn import set_config
set_config(transform_output="pandas")

In [67]:
import pandas as pd

df = pd.read_csv("Documents/MAchine Learning/ML Datasets/WA_Fn-UseC_-HR-Employee-Attrition.csv")
print(df.shape)

(1470, 35)

In [68]:
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [69]:
print(df['Attrition'].value_counts())
print(df['Attrition'].value_counts(normalize=True) * 100)

Attrition
No     1233
Yes     237
Name: count, dtype: int64
Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

In [70]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [72]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [73]:
for col in ["EmployeeCount", "Over18", "StandardHours"]:
    print(col, df[col].unique())

EmployeeCount [1]
Over18 <ArrowStringArray>
['Y']
Length: 1, dtype: str
StandardHours [80]

In [74]:
df = df.drop(columns=["EmployeeCount", "StandardHours", "Over18", "EmployeeNumber"])

In [75]:
df.shape

(1470, 31)

In [76]:
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [77]:
from sklearn.model_selection import train_test_split

X=df.drop("Attrition", axis=1)
Y=df["Attrition"]

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [78]:
y_test.shape

(294,)

In [79]:
numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

In [80]:
categorical_cols = X.select_dtypes(include=["str"]).columns.tolist()

In [81]:
print("Numeric columns:", numeric_cols)
print("Categorical columns:", categorical_cols)

Numeric columns: ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
Categorical columns: ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

In [82]:
df["Education"].unique()

array([2, 1, 4, 3, 5])

In [88]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing  import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
scaling_pipe=Pipeline([
    ("scaling", StandardScaler())
])

onehot_pipe = Pipeline([
    ("onehot", OneHotEncoder(sparse_output=False))
])
ordinal_pipe = Pipeline([
     ("ordinal", OrdinalEncoder(categories = [['Non-Travel','Travel_Rarely', 'Travel_Frequently']]))
 ])

preprocessing = ColumnTransformer([
    ("scaling", scaling_pipe, numeric_cols),
    ("onehot", onehot_pipe, ['Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']),
    ("ordinal", ordinal_pipe, ["BusinessTravel"] )
])

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
full_pipe_lr = Pipeline([
    ("preprocessing", preprocessing),
    ("model_lr", LogisticRegression(random_state=42, max_iter=1000, class_weight='balanced'))
])

full_pipe_rf = Pipeline([
    ("preprocessing", preprocessing),
    ("model_rf", RandomForestClassifier(random_state=42, n_jobs=-1, class_weight='balanced'))
])

full_pipe_xgb = Pipeline([
    ("preprocessing", preprocessing),
    ("model_xgb", XGBClassifier(random_state=42, n_jobs=-1, scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)))
])

In [90]:
param_grid_lr = {
    "model_lr__C": [0.01, 0.1, 1, 10]
}

param_grid_rf = {
    "model_rf__n_estimators": [100, 200],
    "model_rf__max_depth": [None, 10]
}

param_grid_xgb = {
    "model_xgb__n_estimators": [100, 200],
    "model_xgb__max_depth": [3, 5],
    "model_xgb__learning_rate": [0.1, 0.01]
}

In [91]:
from sklearn.model_selection import GridSearchCV

grid_lr = GridSearchCV(full_pipe_lr, param_grid_lr, cv=5, scoring="roc_auc")
grid_rf = GridSearchCV(full_pipe_rf, param_grid_rf, cv=5, scoring="roc_auc")
grid_xgb = GridSearchCV(full_pipe_xgb, param_grid_xgb, cv=5, scoring="roc_auc")

In [92]:
grid_lr.fit(x_train, y_train)
grid_rf.fit(x_train, y_train)
grid_xgb.fit(x_train, y_train)

print("LR best score:", grid_lr.best_score_)
print("RF best score:", grid_rf.best_score_)
print("XGB best score:", grid_xgb.best_score_)

LR best score: 0.8284489295843824
RF best score: 0.7931762859695001
XGB best score: 0.7783583902071747

In [93]:
y_pred_lr = grid_lr.best_estimator_.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.92      0.80      0.86       247
           1       0.38      0.66      0.48        47

    accuracy                           0.78       294
   macro avg       0.65      0.73      0.67       294
weighted avg       0.84      0.78      0.80       294

In [95]:
#"For an HR use case, missing an at-risk employee (false negative) is often costlier than a false alarm (false positive) —
#since a missed departure means losing an employee with no chance to intervene, while a false alarm just means an unnecessary 
#retention conversation. Given this, prioritizing recall over precision is a defensible choice, even though it reduces overall precision."