<a href="https://colab.research.google.com/github/AdityaJare/ML-PRojects/blob/main/HR_Employee_Attrition_ann_keras_tuned.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install tensorflow keras-tuner

Requirement already satisfied: tensorflow in /usr/local/lib/python3.13/dist-packages (2.21.0)
Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (6.33.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from tensorflow) (80.10.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.6.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 9.3 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [97]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.callbacks import Callback
from tensorflow.keras import layers
from keras.layers import Dense, Dropout
import keras_tuner as kt
import matplotlib.pyplot as plt

In [70]:
df = pd.read_csv("/WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [71]:
df.head()

   Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0
3   33        No  ...                       3                     0
4   27        No  ...                       2                     2

[5 rows x 35 columns]

In [72]:
df.shape

(1470, 35)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [74]:
df = df.drop(columns=["EmployeeCount", "Over18", "StandardHours", "EmployeeNumber"])

In [75]:
df.shape

(1470, 31)

In [76]:
df["Attrition"] = df["Attrition"].map({"Yes": 1, "No" : 0})

In [77]:
df

      Age  Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0      41          1  ...                       0                     5
1      49          0  ...                       1                     7
2      37          1  ...                       0                     0
3      33          0  ...                       3                     0
4      27          0  ...                       2                     2
...   ...        ...  ...                     ...                   ...
1465   36          0  ...                       0                     3
1466   39          0  ...                       1                     7
1467   27          0  ...                       0                     3
1468   49          0  ...                       0                     8
1469   34          0  ...                       1                     2

[1470 rows x 31 columns]

In [78]:
X = df.drop(columns="Attrition", axis=1)
y = df["Attrition"]

In [79]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 42, stratify=y)

In [80]:
x_train.head()

      Age     BusinessTravel  ...  YearsSinceLastPromotion YearsWithCurrManager
1194   47      Travel_Rarely  ...                        1                    2
128    22      Travel_Rarely  ...                        2                    1
810    46      Travel_Rarely  ...                        4                    9
478    25      Travel_Rarely  ...                        0                    6
491    43  Travel_Frequently  ...                        4                    7

[5 rows x 30 columns]

In [81]:
numeric_cols= x_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
onehot_cols = ['Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']
ordinal_cols = ['BusinessTravel']

In [82]:
numeric_cols = [c for c in numeric_cols if c not in onehot_cols + ordinal_cols]

In [83]:
# individual preprocessing pipeline

scaling_pipe = Pipeline([
    ("Scaling", StandardScaler())
])

onehot_pipe = Pipeline([
    ("OneHot", OneHotEncoder(handle_unknown="ignore", sparse_output=False, drop="first"))
])

ordinal_pipe = Pipeline([
    ("Ordinal", OrdinalEncoder(categories=[['Non-Travel', 'Travel_Rarely', 'Travel_Frequently']]))
])

In [84]:
# building full preprocessing pipeline

preprocessing = ColumnTransformer([
    ("Scaling", scaling_pipe, numeric_cols),
    ("onehot", onehot_pipe, onehot_cols),
    ("ordinal", ordinal_pipe, ordinal_cols)
])

In [85]:
x_train_preprocessed = preprocessing.fit_transform(x_train)
x_test_preprocessed = preprocessing.transform(x_test)

In [86]:
x_train_preprocessed.shape

(1176, 43)

In [87]:
n_features = x_train_preprocessed.shape[1]

In [92]:
def build_model(hp):

  model = keras.Sequential()

  model.add(layers.Input(shape=(n_features,)))

  for i in range(hp.Int("num_layers" , 1, 3)):

    model.add(Dense(
        units=hp.Int(f"unit{i} ", min_value=16, max_value=128, step=16),
        activation="relu"
    ))

    model.add(Dropout(hp.Float(f"Dropout {i} : ", min_value=0.1, max_value=0.5, step=0.1)))

  model.add(Dense(1, activation="sigmoid"))

  hp_learning_rate= hp.Choice("learning_rate" , values=[0.1, 0.01, 0.001])
  hp_optimizer =  hp.Choice("optimizer" , values=["adam", "rmsprop", "nadam", "sgd"])

  if hp_optimizer == "adam":
    optimizer = keras.optimizers.Adam(learning_rate=hp_learning_rate)
  elif hp_optimizer == "rmsprop":
    optimizer = keras.optimizers.RMSprop(learning_rate=hp_learning_rate)
  elif hp_optimizer == "nadam":
    optimizer = keras.optimizers.Nadam(learning_rate=hp_learning_rate)
  elif hp_optimizer == "sgd":
    optimizer = keras.optimizers.SGD(learning_rate=hp_learning_rate)

  model.compile(
    optimizer = optimizer,
    loss="binary_crossentropy",  # standard loss for binary classification
    metrics=["accuracy", keras.metrics.AUC(name="auc")]
  )
  return model

In [98]:
tuner = kt.RandomSearch(
    build_model,
    objective = kt.Objective("val_auc", direction="max"),
    max_trials = 10,
    executions_per_trial=1,
    directory="keras_tuner_dir",
    project_name="attrition_ann"

)

In [108]:
early_stop = tf.keras.callbacks.EarlyStopping(monitor="val_auc", patience=5, mode="max", restore_best_weights=True
)

In [103]:
tuner.search(
    x_train_preprocessed, y_train,
    validation_split=0.2,
    epochs=50,
    callbacks=[early_stop],
    verbose=1
)

Trial 10 Complete [00h 00m 06s]
val_auc: 0.8466198444366455

Best val_auc So Far: 0.8744897246360779
Total elapsed time: 00h 01m 43s

In [104]:
best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]
print("Best hyperparameters found:")
print(best_hp.values)

Best hyperparameters found:
{'num_layers': 1, 'unit0 ': 128, 'Dropout 0 : ': 0.5, 'learning_rate': 0.01, 'optimizer': 'nadam', 'unit1 ': 80, 'Dropout 1 : ': 0.4, 'unit2 ': 64, 'Dropout 2 : ': 0.30000000000000004}

In [109]:
best_model=tuner.hypermodel.build(best_hp)

In [110]:
history = best_model.fit(
    x_train_preprocessed, y_train,
    epochs=100,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.8330 - auc: 0.6537 - loss: 0.4482 - val_accuracy: 0.8686 - val_auc: 0.8287 - val_loss: 0.3387
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8638 - auc: 0.8133 - loss: 0.3436 - val_accuracy: 0.8686 - val_auc: 0.8455 - val_loss: 0.3227
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8723 - auc: 0.8337 - loss: 0.3250 - val_accuracy: 0.8559 - val_auc: 0.8452 - val_loss: 0.3286
Epoch 4/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8872 - auc: 0.8502 - loss: 0.3066 - val_accuracy: 0.8898 - val_auc: 0.8545 - val_loss: 0.3125
Epoch 5/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8840 - auc: 0.8772 - loss: 0.2859 - val_accuracy: 0.8941 - val_auc: 0.8401 - val_loss: 0.3144
Epoch 6/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8915 - auc: 0.8857 - loss: 0.2770 - val_accuracy: 0.8898 - val_auc: 0.8480 - val_loss: 0.3204
Epoch 7/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9000 - auc: 0.8950 - loss: 0.2667 - val_accuracy: 0.8686 - val_auc: 0.8455 - val_loss: 0.3232
Epoch 8/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9000 - auc: 0.9086 - loss: 0.2466 - val_accuracy: 0.9025 - val_auc: 0.8645 - val_loss: 0.2969
Epoch 9/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9106 - auc: 0.9390 - loss: 0.2179 - val_accuracy: 0.8856 - val_auc: 0.8380 - val_loss: 0.3454
Epoch 10/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9128 - auc: 0.9358 - loss: 0.2208 - val_accuracy: 0.9068 - val_auc: 0.8595 - val_loss: 0.3092
Epoch 11/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9117 - auc: 0.9234 - loss: 0.2274 - val_accuracy: 0.8856 - val_auc: 0.8489 - val_loss: 0.3388
Epoch 12/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9234 - auc: 0.9383 - loss: 0.2057 - val_accuracy: 0.8856 - val_auc: 0.8480 - val_loss: 0.3243
Epoch 13/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9245 - auc: 0.9497 - loss: 0.1922 - val_accuracy: 0.8856 - val_auc: 0.8415 - val_loss: 0.3392

In [112]:
from sklearn.metrics import classification_report

y_pred_proba = best_model.predict(x_test_preprocessed)
y_pred = (y_pred_proba > 0.5).astype(int)

print(classification_report(y_test, y_pred))

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
              precision    recall  f1-score   support

           0       0.88      0.97      0.92       247
           1       0.65      0.32      0.43        47

    accuracy                           0.86       294
   macro avg       0.77      0.64      0.68       294
weighted avg       0.85      0.86      0.84       294